# Generated by Django 4.2.11 on 2024-05-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(default='img/no-image-available.jpg', max_length=200)),
                ('category', models.CharField(default='Autre', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('stars', models.IntegerField(default=0)),
                ('short_description', models.CharField(max_length=400)),
                ('long_description', models.TextField()),
            ],
        ),
    ]
