# Generated by Django 4.2.11 on 2024-05-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_service_service_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
